DROP TABLE IF EXISTS category,events;
CREATE TABLE category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100)
);

CREATE TABLE users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(100)                            NOT NULL,
    email VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE events
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation        VARCHAR(100)                            NOT NULL,
    category          BIGINT                                  NOT NULL
        constraint events_category_id_fk
            references category,
    createdOn         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    description       VARCHAR(512)                            NOT NULL,
    eventDate         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    initiator         BIGINT                                  NOT NULL
--         constraint events_category_id_fk
--             references category
    ,
    location          BIGINT                                  NOT NULL
--         constraint events_category_id_fk
--             references category
    ,
    paid              BOOLEAN                                 NOT NULL,
    participantLimit  BIGINT                                  NOT NULL,
    publishedOn       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    requestModeration BOOLEAN                                 NOT NULL,
    state             BIGINT                                  NOT NULL,
    title             VARCHAR(100)                            NOT NULL
);


CREATE TABLE requests
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event       BIGINT                                  NOT NULL
        constraint requests_events_id_fk
            references events,

    description VARCHAR(512)                            NOT NULL,
    requester   BIGINT                                  NOT NULL
        constraint request_users_id_fk
            references users,

    status      BIGINT                                  NOT NULL,

    CONSTRAINT pk_request PRIMARY KEY (id)
);

-- TODO -добавить таблицы с локациями и компиляциями
--      -добавить ключи




