DROP TABLE IF EXISTS users,category,events,requests,location,compilations,event_compilation,comments;
CREATE TABLE category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_category PRIMARY KEY,
    name VARCHAR(100) NOT NULL

);

CREATE TABLE users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_users PRIMARY KEY,
    name  VARCHAR(300) NOT NULL,
    email VARCHAR(300) NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE location
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_location PRIMARY KEY,

    lat numeric NOT NULL,
    lon numeric NOT NULL
);

CREATE TABLE events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_events PRIMARY KEY,
    annotation         VARCHAR(2000)               NOT NULL,
    category           BIGINT                      NOT NULL
        constraint events_category_id_fk
            references category,
    created_on         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description        VARCHAR(7000)               NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator          BIGINT                      NOT NULL,
    location_id        BIGINT                      NOT NULL
        constraint events_location_id_fk
            references location,
    paid               BOOLEAN                     NOT NULL,
    participant_limit  BIGINT                      NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN                     NOT NULL,
    state              BIGINT                      NOT NULL,
    title              VARCHAR(120)                NOT NULL


);

CREATE TABLE requests
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_requests PRIMARY KEY,
    created   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event     BIGINT                      NOT NULL
        constraint requests_events_id_fk
            references events,
    requester BIGINT                      NOT NULL,

    status    BIGINT                      NOT NULL

);


alter table events
    add confirmed_requests BIGINT
        constraint events_requests_id_fk
            references requests;
;

CREATE TABLE compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_compilations PRIMARY KEY,
    pinned BOOLEAN      NOT NULL,
    title  VARCHAR(100) NOT NULL
);

CREATE TABLE event_compilation
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,

    event       BIGINT NOT NULL
        constraint event_compilation_event_id_fk
            references events,
    compilation BIGINT NOT NULL
        constraint event_compilation_compilations_id_fk
            references compilations
);

CREATE TABLE comments
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event       BIGINT                      NOT NULL
        constraint event_comments_id_fk
            references events,
    commentator BIGINT                      NOT NULL
        constraint comments_users_id_fk
            references users,
    created     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    text        VARCHAR(7000)               NOT NULL
);




