DROP TABLE IF EXISTS statistic;
CREATE TABLE statistic
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app  VARCHAR(100)                            NOT NULL,
    uri VARCHAR(100)                            NOT NULL,
    ip VARCHAR(100)                            NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL
);

