DROP TABLE IF EXISTS statistic;
CREATE TABLE statistic
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(100),
    uri       VARCHAR(100),
    ip        VARCHAR(100),
    timestamp TIMESTAMP WITHOUT TIME ZONE
);

